---
# Config File for JoinUIWorking
# Thanks for using my Plugin

# Use \n to go in a new line
# Use {player} to get player name
# Use § as a color symbole

joinui-title: "§7» §dJoinUI" # UI Title
joinui-message: "§eBun venit pe GXPE {player}!\n§bDistractie plăcută!\n\nGXPE se bazeaza pe secțiunile\n§fPrison,Factions,SkyBlock" # UI Text
joinui-button: "§cInchide" # UI Button

enabled-joinui: "true" # If you set enabled to false, you will no longer see a UI when joining. Default is on true
no-joinui-message: "§l§eServer §r§7» §cJoinUI este dezactivat momentan!" # The Message if you set "enabled-joinui" to false

# My Discord: discord.gg/teMPCyA
...
